### ISSUE TITLE
add plugin to redmine.org plugin repo

### ISSUE THREAD

**Issue by tofi86** [tmy/redmine_gemoji#5]
Hey,
it would be very nice if you could add the plugin to the redmine.org plugin repository at http://www.redmine.org/plugins

I can confirm that it works well with redmine 2.4.x

cheers,
toby

**Comment by tofi86** [comment]
this would be even more important now as redmine 2.5 adds a plugin update check...
but the update check only checks back with the official redmine plugin repo at http://www.redmine.org/plugins

**Comment by dominch** [comment]
plugin don't work on 2.6 :(

**Comment by tofi86** [comment]
@dominch try my fork at https://github.com/paginagmbh/redmine_emojibutton

**Comment by dominch** [comment]
Trying, but have same error with rake: 

<pre>
rake aborted!
stack level too deep
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:240
</pre>

There are more than 30 plugins in my redmine, allmost all work (there are small template conflicts etc), but this is the only one that cause rake error. Do you have any idea how to avoid that?

**Comment by tofi86** [comment]
Closing this issue as the plugin maintainer doesn't seem to maintain this plugin anymore.
Everyone stumbling upon this plugin, use my fork: https://github.com/paginagmbh/redmine_emojibutton

**Comment by tofi86** [comment]
@dominch don't discuss this here. open a new issue in my fork and post your whole environment and the complete stack error. never experienced this, though...
